<?php

namespace App\Repository\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class AdminUser.
 *
 * @package namespace App\Repository\Models;
 */
class AdminUser extends Model implements Transformable
{
    use TransformableTrait;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name','email','password','status','is_super','created_at','updated_at','user_id'];
    protected $appends  = ['user_id'];
    protected $hidden   = ['id'];

    public static function boot() {
        self::creating(function ($user) {
            $user->password = md5($user->password);
        });
//        self::updated(function ($user) {
//            $user->password = md5($user->password);
//        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function getUserIdAttribute($val){
        return $this->id;
    }
}
